### ISSUE TITLE
Handling SSPI

### ISSUE THREAD

**Issue by noblesm19** [tableau/mobile-connected-client#4]
Hi Ron and Team,

If our server is configured for SSO, how can we handle that in the mobile-connected-client? Here's the error that I am running in to in the console:

CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    sdmn = "****";
    srvr = "******";
    sync = syna;
}

Hitting sign-in just spins as if it can't authenticate. 

Any ideas?

**Comment by ronzilla** [comment]
Good question--Tableau Mobile itself doesn't actually support SSPI, but after some conversations internally we think it could be possible. Let me do some detective work.

Is your app able to sign in via a WKWebView?

But the connected clients part fails because its requests aren't authenticated via SSPI?

Thanks!
